# Generated by Django 4.2.4 on 2023-08-23 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ebs_app", "0003_alter_event_event_organiser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_organiser",
        ),
    ]
