# Generated by Django 4.2.4 on 2023-08-23 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("event_organiser", "0001_initial"),
        ("ebs_app", "0004_remove_event_event_organiser"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_organiser",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="event_organiser.eventorganiser",
            ),
        ),
    ]
