# Generated by Django 4.2.4 on 2023-08-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebs_app", "0005_event_event_organiser"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("BOOKED", "Booked"),
                    ("CANCELLED", "Cancelled"),
                    ("PENDING", "Pending"),
                ],
                default="PENDING",
                max_length=20,
                null=True,
            ),
        ),
    ]
