# Generated by Django 4.2.4 on 2023-08-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebs_app", "0006_booking_is_cancelled_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("BOOKED", "Booked"),
                    ("CANCELLED", "Cancelled"),
                    ("PENDING", "Pending"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
