# Generated by Django 4.2.4 on 2023-08-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebs_app", "0008_ticket_total_allotment"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
