# Generated by Django 4.2.4 on 2023-08-28 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ebs_app", "0011_remove_booking_count_remove_booking_ticket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="booking",
            name="sub_bookings",
        ),
        migrations.CreateModel(
            name="SubBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ebs_app.booking",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebs_app.ticket"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="sub_bookings",
            field=models.ManyToManyField(
                related_name="bookings", to="ebs_app.subbooking"
            ),
        ),
    ]
