# Generated by Django 4.2.4 on 2023-08-28 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ebs_app", "0012_booking_total_price_remove_booking_sub_bookings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subbooking",
            name="booking",
        ),
    ]
